sudo: required
services:
    - docker

before_install:
    - docker build -t vijayragavan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vijayragavan/react-test npm test

after_success:
    - docker build -t vijayragavan/multi-client ./client
    - docker build -t vijayragavan/multi-nginx ./nginx
    - docker build -t vijayragavan/multi-server ./server
    - docker build -t vijayragavan/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push vijayragavan/multi-client
    - docker push vijayragavan/multi-nginx
    - docker push vijayragavan/multi-server
    - docker push vijayragavan/multi-worker
    
