version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '3050:80'
        depends_on:
            - api
            - client
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            # Dont override node_modules inside the container
            - /app/node_modules
            # Redirect everything inside /app in the container to ./server (except above dir)
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
        depends_on:
            - postgres
            - redis
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379



